### ISSUE TITLE
【报错】关于某些表情

### ISSUE THREAD

**Issue by Momoi-coder** [noneplugin/nonebot-plugin-memes#100]
/摸 某个QQ保存的表情包就报错
06-10 23:35:45 [WARNING] nonebot_plugin_memes | Traceback (most recent call last):
  File "C:\Users\18280\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\meme.py", line 133, in __call__
    imgs.append(BuildImage.open(image))  # type: ignore
  File "C:\Users\18280\AppData\Local\Programs\Python\Python310\lib\site-packages\pil_utils\build_image.py", line 66, in open
    return cls(Image.open(file))
  File "C:\Users\18280\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002B76519DCB0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18280\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_memes\__init__.py", line 266, in process
    result = await meme(images=images, texts=texts, args=args)
  File "C:\Users\18280\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\meme.py", line 135, in __call__
    raise OpenImageFailed(str(e))
meme_generator.exception.OpenImageFailed: Error in meme_generator: Error opening images: "cannot identify image file <_io.BytesIO object at 0x000002B76519DCB0>"

**Comment by MeetWq** [comment]
这应该是从QQ下载图片的时候下载出错，大概率是你用的机器人协议端的问题

这边先close了，如果还有问题或能稳定复现可以reopen

**Comment by Mechorca** [comment]
可能是协议端那边rkey没有正常获取。协议端需要获取rkey后才可以正常下载图片。打印一下meme中的image信息。没有rkey的时候图片信息是这样的
![a633b2a6e6f9108abdcb00af8db5a48a](https://github.com/user-attachments/assets/2b0097e2-7e18-45dc-8b66-3da40c89d17c)
![image](https://github.com/user-attachments/assets/461e0703-ce8f-46c8-ad94-76b4f0ac22ff)
想办法让协议端可以获取到rkey就可以解决了

**Comment by HolyFishhh** [comment]
> 可能是协议端那边rkey没有正常获取。协议端需要获取rkey后才可以正常下载图片。打印一下meme中的image信息。没有rkey的时候图片信息是这样的 ![a633b2a6e6f9108abdcb00af8db5a48a](https://private-user-images.githubusercontent.com/87187802/361712784-2b0097e2-7e18-45dc-8b66-3da40c89d17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjIxOTIsIm5iZiI6MTcyNjAyMTg5MiwicGF0aCI6Ii84NzE4NzgwMi8zNjE3MTI3ODQtMmIwMDk3ZTItN2UxOC00NWRjLThiNjYtM2RhNDBjODlkMTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMzEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDEzNmEyZGExNDkyZGQ4NjA5ZGE5MTk2MzZmYWFmZDQ2ZDU2NTc1NWE5NmUzMWY4N2JmN2ExMjlmNTY1MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ZF2l_DFmCwkgPplwkoQ1Vv-tkxlkdW2TxC9Q8r0Nwc) ![image](https://private-user-images.githubusercontent.com/87187802/361713221-0cdedcef-102c-4573-b5b8-2d26e79f75c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjIxOTIsIm5iZiI6MTcyNjAyMTg5MiwicGF0aCI6Ii84NzE4NzgwMi8zNjE3MTMyMjEtMGNkZWRjZWYtMTAyYy00NTczLWI1YjgtMmQyNmU3OWY3NWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMzEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMTA1ZDhiM2VlZjkyYTQzNDRjNzZmMDFlYjVmNTFhNjA3NWViNTU1ZjEzMDYxZWY1YjhlNTgxZmRlZGNiMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sb2VBjMdzxe_a97H8YQacV3TLBQk8kUuVIuHblTZo5M)
> 
> 想办法让协议端可以获取到rkey就可以解决了

我也出现了同样的问题，求教一下怎么解决的，使用的lagrange
我的日志中没有出现rkey相关内容
