### ISSUE TITLE
Bug: 严重的滞后问题

### ISSUE THREAD

**Issue by wling-art** [noneplugin/nonebot-plugin-memes#104]
在 https://github.com/orgs/nonebot/discussions/480 讨论中，我得知尝试移除插件恢复滞后问题。
在单独测试此插件时发现了严重滞后的问题，希望得到解决与帮助

**Comment by MeetWq** [comment]
你用的 memes 还是 memes-api ？

**Comment by wling-art** [comment]
都有用过

**Comment by MeetWq** [comment]
是做表情的时候卡还是收到消息就会卡？

**Comment by wling-art** [comment]
收到消息的时候，就是当用户发出关键词，nonebot也接受到消息，但是可能关键词太多的原因？收到信息过一会才能Event will be handled by Matcher xxx

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/blob/ca264036b54be12d3460e318f1180f1b22fe2cc9/nonebot_plugin_memes/__init__.py#L356-L359

可以试着把这几行注释掉，也就是去掉正则匹配，看会不会好一点

**Comment by wling-art** [comment]
> https://github.com/noneplugin/nonebot-plugin-memes/blob/ca264036b54be12d3460e318f1180f1b22fe2cc9/nonebot_plugin_memes/__init__.py#L356-L359
> 
> 可以试着把这几行注释掉，也就是去掉正则匹配，看会不会好一点

欸是啊，好一点了

**Comment by wling-art** [comment]
不，反而是注释上面的key会好一些
https://github.com/noneplugin/nonebot-plugin-memes/blob/ca264036b54be12d3460e318f1180f1b22fe2cc9/nonebot_plugin_memes/__init__.py#L352-L355

**Comment by MeetWq** [comment]
那就是关键词太多导致的。。
我之后看能不能优化一下

**Comment by MeetWq** [comment]
可以试试新版有没有好一点

**Comment by wling-art** [comment]
oo，看起来快多了
tks
