### ISSUE TITLE
Preparing metadata (pyproject.toml) error

### ISSUE THREAD

**Issue by LLingeng** [noneplugin/nonebot-plugin-memes#105]
安装插件时报错了,nb和pip都会报错
小白求解T-T
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c\.mesonpy-qum2rjcl -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c\.mesonpy-qum2rjcl\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c
      Build dir: C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c\.mesonpy-qum2rjcl
      Build type: native build
      Program python3 found: YES
      Project name: matplotlib
      Project version: 3.9.1
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `gcc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang-cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `pgcc --version` gave "[WinError 2] 系统找不到指定的文件。"

      A full log can be found at C:\Users\Ling\AppData\Local\Temp\pip-install-52g4kbk1\matplotlib_4ba332be34054e078e61351cafe0a57c\.mesonpy-qum2rjcl\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MeetWq** [comment]
安装c++编译器
https://matplotlib.org/devdocs/install/dependencies.html#compiled-extensions

**Comment by LLingeng** [comment]
解决了,感谢
