### ISSUE TITLE
@用户依然使用发送者的头像

### ISSUE THREAD

**Issue by LLingeng** [noneplugin/nonebot-plugin-memes#106]
![20240804205055](https://github.com/user-attachments/assets/11a3e1bb-bbed-46a6-9faf-d3d785b7b306)
![20240804210006](https://github.com/user-attachments/assets/2f691ff5-a217-4da4-a792-3b18a679a798)
如图,这是bug还是说不支持@的操作,或者是我的配置问题

**Comment by MeetWq** [comment]
我看到你收到的消息中并没有 @ 相关字段，这不是这个插件的问题，你可以去 [QQ适配器](https://github.com/nonebot/adapter-qq) 问问看

**Comment by MeetWq** [comment]
https://github.com/nonebot/adapter-qq/issues/76
