### ISSUE TITLE
[Bug] 表情包制作命令无法正常显示帮助

### ISSUE THREAD

**Issue by reine-ishyanami** [noneplugin/nonebot-plugin-memes#110]
系统：Ubuntu Server 24.04 LTS 64bit

效果图

![08ef13a831eb9d42fd510e9a4462cf37](https://github.com/user-attachments/assets/cca0aae4-f164-4a69-9d65-b0d8ff5d4d99)

已按 [字体安装](https://github.com/MeetWq/meme-generator/wiki/%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85) 安装字体

**Comment by MeetWq** [comment]
看上去字体长度是正常的，这种情况很奇怪
制作带文字的表情是否正常呢？
你有没有自己改过 `meme-generator` 的代码？

**Comment by reine-ishyanami** [comment]
已解决，把 [全部字体](https://github.com/MeetWq/meme-generator/tree/main/resources/fonts) 都安装了就行，之前用的老版本的字体缺失新版本的一些字体了
