### ISSUE TITLE
看着应该没报错🦆，咋无响应

### ISSUE THREAD

**Issue by 212182815** [noneplugin/nonebot-plugin-memes#113]
![E66386670D5C29E0CB02C5BB183530E2](https://github.com/user-attachments/assets/8a11c62c-754e-41de-9ae9-613fea9e6f13)

**Comment by MeetWq** [comment]
没有配置过命令前缀的话，命令前要加 "/"

**Comment by 212182815** [comment]
> 没有配置过命令前缀的话，命令前要加 "/"

可以了，谢谢
