### ISSUE TITLE
表情包列表显示乱码

### ISSUE THREAD

**Issue by WillyerQ** [noneplugin/nonebot-plugin-memes#114]
系统 Ubuntu20.04LST
问题 显示的表情包列表是乱码
![7T8_M9PPCCYD6 SR53%5$JV](https://github.com/user-attachments/assets/b092d733-824d-40a9-b79c-10a5675080fe)
字体缓存已删除，图片缓存也已经删除了，但是还是显示乱码，而且后台无报错，表情包发出的字体也是正常的
![I}}Z`OIH32R7MO{@OAB7VH1](https://github.com/user-attachments/assets/4eec6746-2211-42e5-8230-a7ebc514efe9)
系统也安装过字体了
![图片](https://github.com/user-attachments/assets/13652368-f9aa-435f-8994-40de664b640f)

搭载机器人：zhenxun_bot v0.1.6.7
使用插件 ：nonebot-plugin-memes-api
期望结果：能正常显示字体

**Comment by 250king** [comment]
同问，是不是还要额外安装什么东西？

**Comment by MeetWq** [comment]
装 https://github.com/MeetWq/meme-generator/tree/main/resources/fonts 里面的字体
