### ISSUE TITLE
希望能适配新版本pil_utils

### ISSUE THREAD

**Issue by billyosoror** [noneplugin/nonebot-plugin-memes#120]
市场部分插件更新后此插件会报pil_util错误，不支持pil_utils-0.2版本，希望能进行适配
![CA12F087B8A52135468B74BDCF10B5C9](https://github.com/user-attachments/assets/ee0348c4-b6bc-41c8-856c-37823f869d99)

**Comment by MeetWq** [comment]
更新 meme-generator
