### ISSUE TITLE
首先报错数据库，安装后报错没找到datastroe，再装遍datastroe找不到icudtl.dat

### ISSUE THREAD

**Issue by xuedu** [noneplugin/nonebot-plugin-memes#129]
![1082c80091b19e2f38a793476a8fd728](https://github.com/user-attachments/assets/0369c6b6-cd93-4352-b217-0bb8a935b3ad)
![18d90848b160e5a74486ecdcaf1cc134](https://github.com/user-attachments/assets/340ddc84-3a69-443f-91f7-95405647061e)
![7393d6851f7c6ddd6b8740700581b8bf](https://github.com/user-attachments/assets/e7770250-3efa-4b29-a616-c0066c14b355)

**Comment by MeetWq** [comment]
datastore 的报错是一次性的，不影响运行
icudtl.dat 这个提示也不影响运行
所以你的问题是什么

**Comment by xuedu** [comment]
> datastore 的报错是一次性的，不影响运行 icudtl.dat 这个提示也不影响运行 所以你的问题是什么

提示找不到icudtl.dat后机器人就自动关闭了...

**Comment by MeetWq** [comment]
这是另一个问题，需要安装 [Visual C++ 运行时](https://visualstudio.microsoft.com/zh-hans/downloads/?q=redistributable#microsoft-visual-c-redistributable-for-visual-studio-2022)
请参考 https://github.com/MeetWq/pil-utils#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

**Comment by xuedu** [comment]
> 这是另一个问题，需要安装 [Visual C++ 运行时](https://visualstudio.microsoft.com/zh-hans/downloads/?q=redistributable#microsoft-visual-c-redistributable-for-visual-studio-2022) 请参考 https://github.com/MeetWq/pil-utils#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

好的 我现在试试

**Comment by MeetWq** [comment]
vc++运行时装了吗？如果还是不行试试 `pip install msvc-runtime`

**Comment by xuedu** [comment]
> vc++运行时装了吗？如果还是不行试试 `pip install msvc-runtime`

已经按照链接装过了 我现在试试你这条  直接在项目根目录下运行吗还是再根目录虚拟环境

**Comment by xuedu** [comment]
还是不行=-=

**Comment by MeetWq** [comment]
当然要进虚拟环境

**Comment by xuedu** [comment]
运行机器人时还剩报错11-29 21:54:14 [ERROR] uvicorn | Application startup failed. Exiting.后关闭

**Comment by MeetWq** [comment]
加主页QQ群说。

**Comment by xuedu** [comment]
好的
