### ISSUE TITLE
请教一下，新版本更新后好几个表情包无法使用。

### ISSUE THREAD

**Issue by babytotdd** [noneplugin/nonebot-plugin-memes#20]
重新更新了之后，部分GIF输入指令后，不触发send_msg，

发送:启用表情 你好骚啊
bot,re:表情 你好骚啊 不存在！
bot,re:表情 你好骚啊 不存在！

现状
资源文件→ github上直接下载更新
site-packages版本号：nonebot_plugin_memes-0.3.5

**Comment by MeetWq** [comment]
gif这类的指令改了，需要“你好骚啊.gif”

**Comment by babytotdd** [comment]
> 

:) 👍  谢谢~！
