### ISSUE TITLE
插件运行报错

### ISSUE THREAD

**Issue by NanakoOfficial** [noneplugin/nonebot-plugin-memes#21]
from nonebot_plugin_imageutils.gradient import ColorStop, LinearGradient
ModuleNotFoundError: No module named 'nonebot_plugin_imageutils.gradient'

nonebot_plugin_imageutils 已安装最新版本

**Comment by MeetWq** [comment]
看看 nonebot_plugin_imageutils 的版本
需要安装最新版：0.1.13

**Comment by NanakoOfficial** [comment]
> 看看 nonebot_plugin_imageutils 的版本 需要安装最新版：0.1.13

我在pip里安装最新只有nonebot-plugin-imageutils-0.1.9
