### ISSUE TITLE
图库下载失败有什么解决办法吗

### ISSUE THREAD

**Issue by NealScx** [noneplugin/nonebot-plugin-memes#23]
nonebot_plugin_memes | https://fastly.jsdelivr.net/gh/noneplugin/nonebot-plugin-memes@vv0.3.x/resources/thumbs/meteor.jpg 下载失败！
11-10 19:18:35 [WARNING] nonebot_plugin_memes | Error downloading https://fastly.jsdelivr.net/gh/noneplugin/nonebot-plugin-memes@vv0.3.x/resources/thumbs/pornhub.jpg, retry 0/3: Redirect response '301 Moved Permanently' for url 'https://fastly.jsdelivr.net/gh/noneplugin/nonebot-plugin-memes@vv0.3.x/resources/thumbs/pornhub.jpg'
Redirect location: 'https://raw.githubusercontent.com/noneplugin/nonebot-plugin-memes/0.3.8/resources/thumbs/pornhub.jpg'
For more information check: https://httpstatuses.com/301

**Comment by MeetWq** [comment]
升级到最新版
