### ISSUE TITLE
无法加载字体

### ISSUE THREAD

**Issue by Harry-Jing** [noneplugin/nonebot-plugin-memes#25]
运行环境为ubuntu server 22.04, python3.10, poetry

![image](https://user-images.githubusercontent.com/69247286/201337885-66930713-3dbb-4132-b43d-56eca78638bb.png)

**Comment by MeetWq** [comment]
这些字体并不是全都要装的
[nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 预先设置了一个字体列表，会从列表中选择可用的字体
