### ISSUE TITLE
低语不管几个字都是过长

### ISSUE THREAD

**Issue by forchannot** [noneplugin/nonebot-plugin-memes#26]
![image](https://user-images.githubusercontent.com/100580891/201522341-e8859e2a-9225-4db7-bad3-40cc2aa37557.png)

**Comment by izaynpan** [comment]
同

**Comment by MeetWq** [comment]
最新版调整了最小字体大小，试试看还有没有问题

**Comment by forchannot** [comment]
> 最新版调整了最小字体大小，试试看还有没有问题

![image](https://user-images.githubusercontent.com/100580891/204802046-51a547cc-6342-4c67-80be-bba1e130107f.png)
似乎还是不行
![image](https://user-images.githubusercontent.com/100580891/204801999-9ea8c1de-2bd5-4503-9276-f1a88f56a1c5.png)

**Comment by MeetWq** [comment]
是图片有问题，已经更新了
