### ISSUE TITLE
Nonebot无法正确识别与执行指令

### ISSUE THREAD

**Issue by chazikaifa** [noneplugin/nonebot-plugin-memes#27]
最近刚搭建的Nonebot2, 该插件无法正常运行，求大佬解答。

Nonebot2基于mirai2与qq连接，log显示可以正常接收信息，但是无法正确回复。

 - 相关log截图如下：
![image](https://user-images.githubusercontent.com/17249736/201992959-9451609d-c9e9-4f5a-9b45-b9a93fcc6c89.png)
  在私聊中输入“文字表情包”，可以被识别，但无回应（`Handler Dependent(call=_) skipped`）
  输入示例指令“鲁迅说 我没说过这句话”， 无法被识别（没有match）

 - 相关配置
   - .env 除mirai配置外仅添加 `COMMAND_START=["/", ""]`
   - 插件调用方式为`pyproject.toml`中添加插件（使用命令`nb plugin install`），`bot.py` 中无修改

请问我的配置方式是否正确，或者是否有什么遗漏的配置？多谢大佬！

**Comment by chazikaifa** [comment]
补充一些可能有用的版本信息：
 - 系统：CentOS 7
 - python：3.8.13
 - nb-cli==0.6.7
 - nonebot2==2.0.0rc1
 - nonebot-adapter-mirai2==0.0.17
 - websockets==10.4
 - nonebot-plugin-imageutils==0.1.13.3
 - nonebot-plugin-memes==0.3.8
 - playwright==1.27.1
 - python-dotenv==0.21.0

**Comment by MeetWq** [comment]
你是用的mirai2的adapter吗？

**Comment by MeetWq** [comment]
这个并没有适配mirai的adapter

**Comment by chazikaifa** [comment]
了解了，多谢大佬

> 这个并没有适配mirai的adapter
