### ISSUE TITLE
配置项 描述和实现有误

### ISSUE THREAD

**Issue by Ikaros-521** [noneplugin/nonebot-plugin-memes#30]
```
memes_command_start
类型：List[str]
默认：[""]
```
![image](https://user-images.githubusercontent.com/40910637/209760234-a645856e-2305-4a89-a87c-4fea56b6ea98.png)

实际上不是List是str

**Comment by MeetWq** [comment]
一开始是str，后来改成List[str]了，更新一下

**Comment by Ikaros-521** [comment]
> 一开始是str，后来改成List[str]了，更新一下

好好好

**Comment by ubby** [comment]
同样的错误，使用的默认项
