### ISSUE TITLE
py3.9资源图片无法下载

### ISSUE THREAD

**Issue by awkks** [noneplugin/nonebot-plugin-memes#36]
![%%3L~}{LC~P%9K54DM4 1TP](https://user-images.githubusercontent.com/110983491/224466213-139dffd7-17a0-4ffa-8cd7-383a7d7a7d42.jpg)
已解决，更换py3.10可正常下载

**Comment by MeetWq** [comment]
是 meme-generator 的问题，目前已修复 https://github.com/MeetWq/meme-generator/issues/6
