### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Astolfocat** [noneplugin/nonebot-plugin-memes#37]
建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包

**Comment by Satori3rdEye** [comment]
可使用 “@ + 用户id” 指定任意用户获取头像，如 “摸 @114514”

**Comment by Satori3rdEye** [comment]
> 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包



> 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包

可使用 “@ + 用户id” 指定任意用户获取头像，如 “摸 @114514”

**Comment by Satori3rdEye** [comment]
> 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包



> 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包

可使用 “@ + 用户id” 指定任意用户获取头像，如 “摸 @114514”

**Comment by Astolfocat** [comment]
> > 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包
> 
> > 建议增加以前那样，指令后跟QQ号也可触发，毕竟艾特有点扰民，有时候想做不是这个群的人的表情包
> 
> 可使用 “@ + 用户id” 指定任意用户获取头像，如 “摸 @114514”

喔原来如此，谢谢啦
