### ISSUE TITLE
随机表情@去哪里了捏

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [noneplugin/nonebot-plugin-memes#38]
如题，之前petpet的随机表情 没有了捏，希望能加上ozr

**Comment by Umamusume-Agnes-Digital** [comment]
还有一个，就是原petpet表情里，指令+qq号的功能也没有了捏，不能虚空索敌了）

**Comment by MeetWq** [comment]
> 还有一个，就是原petpet表情里，指令+qq号的功能也没有了捏，不能虚空索敌了）

现在改成 “@ + qq号” 了，readme 中有写

**Comment by MeetWq** [comment]
已加，新版本已发布
