### ISSUE TITLE
文字表情包预订

### ISSUE THREAD

**Issue by jcjrobert** [noneplugin/nonebot-plugin-memes#4]
因为属于文字类这里也开一个

①输入一句话，类似以下形式进行滚屏
![69fef1894a87df9d](https://user-images.githubusercontent.com/52129454/149624742-e31e2405-b254-491f-b4f1-b311c5a2fc0e.gif)

**Comment by jcjrobert** [comment]
②一巴掌
![1ee487a3ea7646f7b25a116e50a73cbe](https://user-images.githubusercontent.com/52129454/149626375-80adb67e-8c85-4001-890b-1c3c894b1d24.jpg)

③别说了
![20220113045451_njlcId](https://user-images.githubusercontent.com/52129454/149626385-e88349f0-db2d-4775-9914-7635807a8b34.jpg)

**Comment by jcjrobert** [comment]
哦对，动图可以默认原句么，或者显示在帮助里（）

**Comment by MeetWq** [comment]
显示在帮助里感觉会很长，我再想想看有没有更合适的方式

**Comment by zhzRedstone** [comment]
https://5000choyen.mikuac.com/image?top=%E7%AB%8B%E5%8D%B3%E4%BD%BF%E7%94%A8&bottom=Nonebot2
这个

**Comment by leinlin** [comment]
![图片](https://user-images.githubusercontent.com/30318270/159357939-34c204c6-1f91-4879-9eb5-8d597f08deb9.png)

**Comment by jcjrobert** [comment]
![-6401cbef41bc5cb7](https://user-images.githubusercontent.com/52129454/160452779-2bdb31f4-8dce-4802-a862-9c6568695a87.gif)
瞧瞧说

**Comment by jcjrobert** [comment]
![DA{{DK~SI}WGVI5DIE~7L6](https://user-images.githubusercontent.com/52129454/173552518-88970f37-d7ed-43fa-b12c-8c3c2cbf5eaa.jpg)
我们群主敢XX

**Comment by yoiyami96** [comment]
许愿失败
<img src = 'https://s3.bmp.ovh/imgs/2022/07/03/36135aef96695860.jpg' />
整点薯条
<img src = 'https://s3.bmp.ovh/imgs/2022/07/03/3847edd710f5dfa3.jpg' />
海鸥叫
<img src = 'https://s3.bmp.ovh/imgs/2022/07/03/9abc9f30bdf52fd5.jpg' />

**Comment by Danwk2333** [comment]
![AFB90C4B051B12C29995A97BAC03B6CF](https://user-images.githubusercontent.com/106854600/178086880-deb55b93-50ab-4c2d-8504-af2cf6a9f172.jpg)
![01861BE189DAC1D78E21100CF6077568](https://user-images.githubusercontent.com/106854600/178086883-512238e0-66d6-4d74-bfda-ba4a9f6f7afd.jpg)
快逃 文字1
![210814013568EF8838EC2424A44610C6](https://user-images.githubusercontent.com/106854600/178086896-dba563a7-cb81-44ab-b920-e59a306573b2.jpg)
哭跑 文字1 文字2
![056CABAA7A2CAF4B7916EA3E01C8DC78](https://user-images.githubusercontent.com/106854600/178086909-79e304f5-dc63-42db-853a-b35af4404eb0.jpg)
音量 文字1 文字2 文字3
![EC245890DFA9E765495A28E4B1430EB3](https://user-images.githubusercontent.com/106854600/178086927-1b47a2c3-c4bc-4dc3-ba18-244a4f4db4a4.jpg)

**Comment by jcjrobert** [comment]
> ![AFB90C4B051B12C29995A97BAC03B6CF](https://user-images.githubusercontent.com/106854600/178086880-deb55b93-50ab-4c2d-8504-af2cf6a9f172.jpg) ![01861BE189DAC1D78E21100CF6077568](https://user-images.githubusercontent.com/106854600/178086883-512238e0-66d6-4d74-bfda-ba4a9f6f7afd.jpg) 快逃 文字1 ![210814013568EF8838EC2424A44610C6](https://user-images.githubusercontent.com/106854600/178086896-dba563a7-cb81-44ab-b920-e59a306573b2.jpg) 哭跑 文字1 文字2 ![056CABAA7A2CAF4B7916EA3E01C8DC78](https://user-images.githubusercontent.com/106854600/178086909-79e304f5-dc63-42db-853a-b35af4404eb0.jpg) 音量 文字1 文字2 文字3 ![EC245890DFA9E765495A28E4B1430EB3](https://user-images.githubusercontent.com/106854600/178086927-1b47a2c3-c4bc-4dc3-ba18-244a4f4db4a4.jpg)

没水印的和使用例有嘛

**Comment by fluorescia** [comment]
![TRUMP](https://user-images.githubusercontent.com/104306794/187009867-e7de5491-8313-410d-8601-6dfd05ab2066.gif)

**Comment by liuzj288** [comment]
![1f0f16d5e0104b439f584c4e0a45a7041664718208689](https://user-images.githubusercontent.com/13833404/193486842-c77ec3d9-3095-45ba-9745-4ff79c9ba5cb.jpeg)
大鸭鸭举牌预定

**Comment by MeetWq** [comment]
> ![1f0f16d5e0104b439f584c4e0a45a7041664718208689](https://user-images.githubusercontent.com/13833404/193486842-c77ec3d9-3095-45ba-9745-4ff79c9ba5cb.jpeg) 大鸭鸭举牌预定

这个有示例吗？我不知道该用什么字体

**Comment by liuzj288** [comment]
> > ![1f0f16d5e0104b439f584c4e0a45a7041664718208689](https://user-images.githubusercontent.com/13833404/193486842-c77ec3d9-3095-45ba-9745-4ff79c9ba5cb.jpeg) 大鸭鸭举牌预定
> 
> 这个有示例吗？我不知道该用什么字体
![image](https://user-images.githubusercontent.com/13833404/193710689-4d8b5eb6-f59b-40cd-8eff-5a3052d1cbb0.png)
![image](https://user-images.githubusercontent.com/13833404/193710714-bda9e22b-1cc3-40e2-af56-5d55853e8396.png)

![image](https://user-images.githubusercontent.com/13833404/193710582-abfc93e2-01b7-4d6f-a7e6-842d6f8b66ae.png)

**Comment by liuzj288** [comment]
> > ![1f0f16d5e0104b439f584c4e0a45a7041664718208689](https://user-images.githubusercontent.com/13833404/193486842-c77ec3d9-3095-45ba-9745-4ff79c9ba5cb.jpeg) 大鸭鸭举牌预定
> 
> 这个有示例吗？我不知道该用什么字体

模板原作者地址
https://www.pixiv.net/artworks/95121746

**Comment by Plasma4004** [comment]
![F4D6C7FD-AD92-4F2E-9C41-FD484C632B7E](https://user-images.githubusercontent.com/110027790/211209563-5f0fde9a-bb3c-4e1e-bc1e-acfbb0cebf49.jpeg)
电信广告
