### ISSUE TITLE
字符画 手机搭建会错位

### ISSUE THREAD

**Issue by CUZNIL** [noneplugin/nonebot-plugin-memes#40]
![MK%_TVEG_G MD}IQCW8U`RJ](https://user-images.githubusercontent.com/76582404/227854057-1bd5a442-13d7-4337-9ec4-a4dfc5622c34.png)

如图，似乎是手机搭建才会出现的问题，在电脑搭建没有确认到相同情况

![V)(GCHV 0`FHSRROD7 9F~4](https://user-images.githubusercontent.com/76582404/227854269-57c348d6-1715-48a2-a800-461d1aa3200a.gif)

下图是运行日志，没有确认到可能有用的信息，就是检测消息就发了。

![H~4RTKM@ @)9(3OOUWZ OI0](https://user-images.githubusercontent.com/76582404/227854507-8feb887c-fc58-4016-8d7f-fa9c263bf3bd.jpg)

**Comment by MeetWq** [comment]
https://github.com/MeetWq/meme-generator/issues/14

**Comment by CUZNIL** [comment]
> [MeetWq/meme-generator#14](https://github.com/MeetWq/meme-generator/issues/14)

因为BOT目录的data/fonts下面有这些字体，我以为不用额外安装orz。
为所有用户安装这个字体以后解决了，请问其他字体也需要手动为所有用户安装吗？

**Comment by MeetWq** [comment]
https://github.com/MeetWq/meme-generator/tree/main/resources/fonts 这些字体需要手动安装

**Comment by CUZNIL** [comment]
> https://github.com/MeetWq/meme-generator/tree/main/resources/fonts 这些字体需要手动安装

好的，谢谢
![N99S09M6}(XP3002W_7GF68](https://user-images.githubusercontent.com/76582404/227866380-5c60534f-eccd-4477-ac5c-085fabe2eaca.jpg)
