### ISSUE TITLE
请问如何屏蔽指定人或指定群，可以简略说一下改动那些地方吗

### ISSUE THREAD

**Issue by LoCCai** [noneplugin/nonebot-plugin-memes#42]

**Comment by jcjrobert** [comment]
这是插件管理该做的事，与本插件无关
如果你想固定使用人和群，可以在__init__.py修改权限，不过应该不符合你的需求

**Comment by MeetWq** [comment]
可以使用插件管理类插件，如 https://github.com/nonepkg/nonebot-plugin-manager
