### ISSUE TITLE
表情包制作帮助图片乱码

### ISSUE THREAD

**Issue by Tuio21** [noneplugin/nonebot-plugin-memes#43]
![-1ee77d73913c93cf](https://user-images.githubusercontent.com/66133655/230056738-f4764e9d-65ab-44c5-83fc-be23db026d8c.jpg)
为什么会这样，其他用着都没问题，表情也没问题就是这个有问题

**Comment by MeetWq** [comment]
装字体

**Comment by maoxig** [comment]
如果你的字体已经安装好了，可以试着去删掉这张帮助图片的缓存，路径参考插件[nonebot_plugin_localstore](https://github.com/nonebot/plugin-localstore)的缓存目录，我猜测是因为https://github.com/noneplugin/nonebot-plugin-memes/blob/4bea7a8439ff30ba99544638d8ae7931154f9d94/nonebot_plugin_memes/__init__.py#L132-L137
你应该是生成乱码的帮助图后才成功安装上字体，而这张图片没有清除掉，导致发送了之前生成的乱码图。如果删掉这张图片后仍是乱码，那么应该是你字体的问题
这个问题我也出现了，删掉后就没问题了
