### ISSUE TITLE
添加插件后日志等级变成TRACE

### ISSUE THREAD

**Issue by UKMeng** [noneplugin/nonebot-plugin-memes#48]
## 环境

- 安装方式：
  1. 通过 nb-cli 安装
  2. 使用 poetry安装
- 操作系统：macOS 13.3.1
- 相关库版本
```
Package                   Version
------------------------- -----------
anyio                     3.6.2
bbcode                    1.1.0
certifi                   2022.12.7
click                     8.1.3
contourpy                 1.0.7
cycler                    0.11.0
dateparser                1.1.8
fastapi                   0.95.1
filetype                  1.2.0
fonttools                 4.39.3
h11                       0.14.0
httpcore                  0.17.0
httptools                 0.5.0
httpx                     0.24.0
idna                      3.4
kiwisolver                1.4.4
loguru                    0.6.0
matplotlib                3.7.1
meme-generator            0.0.10
msgpack                   1.0.5
multidict                 6.0.4
nonebot-adapter-onebot    2.2.3
nonebot-plugin-localstore 0.4.1
nonebot-plugin-memes      0.4.5
nonebot2                  2.0.0rc4
numpy                     1.24.3
opencv-python-headless    4.7.0.72
packaging                 23.1
pil-utils                 0.1.7
Pillow                    9.5.0
pip                       22.3.1
pydantic                  1.10.7
pygtrie                   2.5.0
pyparsing                 3.0.9
pypinyin                  0.48.0
python-dateutil           2.8.2
python-dotenv             1.0.0
python-multipart          0.0.5
pytz                      2023.3
pytz-deprecation-shim     0.1.0.post0
PyYAML                    6.0
regex                     2023.3.23
setuptools                65.6.3
six                       1.16.0
sniffio                   1.3.0
starlette                 0.26.1
toml                      0.10.2
tomli                     2.0.1
tqdm                      4.65.0
typing_extensions         4.5.0
tzdata                    2023.3
tzlocal                   4.3
uvicorn                   0.22.0
uvloop                    0.17.0
watchfiles                0.19.0
websockets                11.0.2
wheel                     0.38.4
yarl                      1.9.2
```

## 问题

在添加插件后（在`pyproject.toml`的`plugins`添加`["nonebot_plugin_memes"]`后，运行`nb run`，输出的日志从原先的`INFO`等级变成`TRACE`等级，且不能通过在`.env.prod`中添加`LOG_LEVEL`的方式修改。删除插件后日志回到原来的等级。

对正常使用没有影响，不过`nb docker generate`在日志等级为`TRACE`的时候会报错。

## 日志

```
ukm@ukmdeMacBook-Air test-meme % nb run
使用 Python: /Users/ukm/Developer/Python/NoneBot/test-meme/.venv/bin/python
04-28 15:46:27 [SUCCESS] nonebot | NoneBot is initializing...
04-28 15:46:27 [INFO] nonebot | Current Env: prod
04-28 15:46:27 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
04-28 15:46:27 [INFO] meme_generator | Config Path: /Users/ukm/Library/Application Support/meme_generator/config.toml
04-28 15:46:42 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:42 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:43 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [TRACE] nonebot | Define new matcher Matcher(type='message', module=nonebot_plugin_memes)
04-28 15:46:44 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_memes"
04-28 15:46:44 [SUCCESS] nonebot | Running NoneBot...
04-28 15:46:44 [DEBUG] nonebot | Loaded adapters: OneBot V11
04-28 15:46:44 [INFO] uvicorn | Started server process [13340]
04-28 15:46:44 [INFO] uvicorn | Waiting for application startup.
04-28 15:46:44 [INFO] nonebot_plugin_memes | 正在检查资源文件...
后略
```

**Comment by webjoin111** [comment]
相同情况

**Comment by MeetWq** [comment]
升级 `meme-generator` 到最新版

**Comment by UKMeng** [comment]
解决了 谢谢大佬！

**Comment by Poick01** [comment]
更新到最新版后日志等级仍然为TRACE
安装方式通过nb-cli安装
相关库版本：
`Package                               Version
------------------------------------- ----------------
aiofiles                              23.2.1
aiohttp                               3.8.6
aiosignal                             1.3.1
aiosqlite                             0.19.0
alembic                               1.12.0
anyio                                 3.7.1
APScheduler                           3.10.4
arclet-alconna                        1.7.28
arclet-alconna-tools                  0.6.7
argcomplete                           3.1.2
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
arrow                                 1.2.3
asttokens                             2.4.0
async-lru                             2.0.4
async-timeout                         4.0.3
asyncio                               3.4.3
attrs                                 23.1.0
Automat                               20.2.0
Babel                                 2.12.1
backcall                              0.2.0
bbcode                                1.1.0
bcrypt                                3.2.0
beautifulsoup4                        4.12.2
bleach                                6.0.0
blinker                               1.4
brial                                 1.0.2
build                                 0.10.0
CacheControl                          0.13.1
certifi                               2020.6.20
cffi                                  1.15.1
chardet                               4.0.0
charset-normalizer                    3.2.0
cleo                                  2.0.1
click                                 8.0.3
cloud-init                            23.2.1
colorama                              0.4.4
comm                                  0.1.4
command-not-found                     0.3
configobj                             5.0.6
constantly                            15.1.0
contourpy                             1.1.1
crashtest                             0.4.1
cryptography                          3.4.8
cycler                                0.12.1
dateparser                            1.1.8
dbus-python                           1.2.18
debugpy                               1.8.0
decorator                             5.1.1
defusedxml                            0.7.1
distlib                               0.3.7
distro                                1.7.0
distro-info                           1.1build1
dulwich                               0.21.6
emoji                                 2.8.0
exceptiongroup                        1.1.3
executing                             1.2.0
fastapi                               0.103.2
fastjsonschema                        2.18.0
filelock                              3.12.4
filetype                              1.2.0
fonttools                             4.43.1
fqdn                                  1.5.1
frozenlist                            1.4.0
greenlet                              2.0.2
gyp                                   0.1
h11                                   0.14.0
h2                                    4.1.0
hpack                                 4.0.0
httpcore                              0.16.3
httplib2                              0.20.2
httptools                             0.6.0
httpx                                 0.23.3
hyperframe                            6.0.1
hyperlink                             21.0.0
idna                                  3.3
importlib-metadata                    6.8.0
incremental                           21.3.0
installer                             0.7.0
ipykernel                             6.25.2
ipython                               8.15.0
isoduration                           20.11.0
jaraco.classes                        3.3.0
jedi                                  0.19.0
jeepney                               0.7.1
jieba                                 0.42.1
jieba-fast                            0.53
Jinja2                                3.0.3
json5                                 0.9.14
jsonpatch                             1.32
jsonpointer                           2.0
jsonschema                            4.17.3
jsonschema-specifications             2023.7.1
jupyter_client                        8.3.1
jupyter_core                          5.3.1
jupyter-events                        0.7.0
jupyter-lsp                           2.2.0
jupyter_server                        2.7.3
jupyter_server_terminals              0.4.4
jupyterlab                            4.0.6
jupyterlab-pygments                   0.2.2
jupyterlab_server                     2.25.0
keyring                               24.2.0
kiwisolver                            1.4.5
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
loguru                                0.7.2
Mako                                  1.2.4
Markdown                              3.5
markdown-it-py                        3.0.0
MarkupSafe                            2.0.1
matplotlib                            3.8.0
matplotlib-inline                     0.1.6
mdurl                                 0.1.2
meme-generator                        0.0.16
meson                                 0.61.2
mistune                               3.0.1
more-itertools                        8.10.0
msgpack                               1.0.7
multidict                             6.0.4
nbclient                              0.8.0
nbconvert                             7.8.0
nbformat                              5.9.2
nepattern                             0.5.15
nest-asyncio                          1.5.8
netifaces                             0.11.0
nonebot-adapter-onebot                2.3.1
nonebot-plugin-alconna                0.28.0
nonebot-plugin-answersbook            0.2.0
nonebot-plugin-apscheduler            0.3.0
nonebot-plugin-capoo                  0.1.4
nonebot-plugin-cesaa                  0.1.0
nonebot_plugin_chatrecorder           0.4.2
nonebot-plugin-colormind              0.1.0
nonebot-plugin-couplets               0.2.0
nonebot_plugin_crazy_thursday         0.2.8
nonebot-plugin-datastore              1.1.2
nonebot-plugin-hitokoto               0.2.1
nonebot-plugin-htmlrender             0.2.2
nonebot-plugin-imagetools             0.2.1
nonebot-plugin-localstore             0.5.1
nonebot-plugin-memes                  0.4.7
nonebot-plugin-person                 0.0.5
nonebot-plugin-RealESRGAN             0.2.6
nonebot-plugin-remake                 0.3.3
nonebot-plugin-send-anything-anywhere 0.3.2
nonebot-plugin-session                0.1.0
nonebot-plugin-wordcloud              0.5.2
nonebot2                              2.1.1
notebook_shim                         0.2.3
numpy                                 1.26.1
oauthlib                              3.2.0
opencv-python-headless                4.8.1.78
overrides                             7.4.0
packaging                             21.3
pandocfilters                         1.5.0
parso                                 0.8.3
pexpect                               4.8.0
pickleshare                           0.7.5
pil-utils                             0.1.8
Pillow                                9.5.0
pip                                   23.2.1
pipx                                  1.2.0
pkginfo                               1.9.6
platformdirs                          3.11.0
playwright                            1.38.0
pluggy                                0.13.0
poetry                                1.6.1
poetry-core                           1.7.0
poetry-plugin-export                  1.5.0
prometheus-client                     0.17.1
prompt-toolkit                        3.0.39
psutil                                5.9.5
ptyprocess                            0.7.0
pure-eval                             0.2.2
py                                    1.10.0
pyasn1                                0.4.8
pyasn1-modules                        0.2.1
pycparser                             2.21
pydantic                              1.10.13
pyee                                  9.0.4
Pygments                              2.16.1
PyGObject                             3.42.1
pygtrie                               2.5.0
PyHamcrest                            2.0.2
PyJWT                                 2.3.0
pymdown-extensions                    10.3
pyOpenSSL                             21.0.0
pyparsing                             2.4.7
pypinyin                              0.49.0
pyproject_hooks                       1.0.0
pyrsistent                            0.18.1
pyserial                              3.5
python-apt                            2.4.0+ubuntu1
python-dateutil                       2.8.2
python-debian                         0.1.43+ubuntu1.1
python-dotenv                         1.0.0
python-json-logger                    2.0.7
python-magic                          0.4.24
python-markdown-math                  0.8
python-multipart                      0.0.6
pytz                                  2022.1
PyYAML                                5.4.1
pyzmq                                 25.1.1
rapidfuzz                             2.15.2
referencing                           0.30.2
regex                                 2023.10.3
requests                              2.31.0
requests-toolbelt                     1.0.0
rfc3339-validator                     0.1.4
rfc3986                               1.5.0
rfc3986-validator                     0.1.1
rich                                  13.6.0
rpds-py                               0.10.3
SecretStorage                         3.3.1
Send2Trash                            1.8.2
service-identity                      18.1.0
setuptools                            59.6.0
shellingham                           1.5.3
six                                   1.16.0
sniffio                               1.3.0
sos                                   4.4
soupsieve                             2.5
SQLAlchemy                            2.0.22
ssh-import-id                         5.11
stack-data                            0.6.2
starlette                             0.27.0
StrEnum                               0.4.15
systemd-python                        234
tarina                                0.4.2
terminado                             0.17.1
tinycss2                              1.2.1
toml                                  0.10.2
tomli                                 2.0.1
tomlkit                               0.12.1
tornado                               6.3.3
tox                                   3.21.4
traitlets                             5.10.0
trove-classifiers                     2023.9.19
Twisted                               22.1.0
typing_extensions                     4.7.1
tzdata                                2023.3
tzlocal                               5.1
ubuntu-advantage-tools                8001
ubuntu-drivers-common                 0.0.0
ufw                                   0.36.1
ujson                                 5.8.0
unattended-upgrades                   0.1
uri-template                          1.3.0
urllib3                               1.26.5
userpath                              1.9.1
uvicorn                               0.23.2
uvloop                                0.18.0
virtualenv                            20.24.5
wadllib                               1.3.6
watchfiles                            0.21.0
wcwidth                               0.2.6
webcolors                             1.13
webencodings                          0.5.1
websocket-client                      1.6.3
websockets                            11.0.3
wheel                                 0.37.1
wordcloud                             1.9.2
xkit                                  0.0.0
yarl                                  1.9.2
zipp                                  1.0.0
zope.interface                        5.4.0`
