### ISSUE TITLE
字体安装位置

### ISSUE THREAD

**Issue by verynewabie** [noneplugin/nonebot-plugin-memes#49]
字体是安装在imageutils插件指定的位置吗

**Comment by verynewabie** [comment]
中文字体是自己随便安装一个就行吗？

**Comment by MeetWq** [comment]
看这里的说明
https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85
