### ISSUE TITLE
[BUG]安装字体后，表情菜单显示口口

### ISSUE THREAD

**Issue by lyyqqw** [noneplugin/nonebot-plugin-memes#53]
已按照要求安装字体
系统：Ubuntu
驱动器：Onebot V11

**Comment by jcjrobert** [comment]
把字体缓存清一下重启
https://github.com/MeetWq/meme-generator/blob/main/docs/install.md

**Comment by SherkeyXD** [comment]
可以看看#43的最后一条

**Comment by BiologyHazard** [comment]
> 把字体缓存清一下重启 https://github.com/MeetWq/meme-generator/blob/main/docs/install.md

我也遇到并且无法解决
