### ISSUE TITLE
插件报错刷屏

### ISSUE THREAD

**Issue by WindraiteLesd** [noneplugin/nonebot-plugin-memes#54]
![IMG_20230603_102408](https://github.com/noneplugin/nonebot-plugin-memes/assets/104503043/88403229-2161-42db-9281-25db9e934428)
![IMG_20230603_102429](https://github.com/noneplugin/nonebot-plugin-memes/assets/104503043/4f2b3464-8a73-46a0-9361-6246abb5c044)
bot启动运行一段时间后基本就是这两种报错循环刷屏，期间无法响应任何指令

**Comment by MeetWq** [comment]
看看是什么收到什么消息导致的报错？

**Comment by WindraiteLesd** [comment]
> 看看是什么收到什么消息导致的报错？

应该是频道消息，nb那里显示的是event has no message
我是yunzai和nb同时用的，因为gocqhttp最近登不上，现在的解决方案协议版本和icqq相同了会互踢，为了能够同时使用，我用的yunzai那边的ws插件去连接的nonebot，ws插件暂时不支持频道消息，会报错，可能和这个有关系？

**Comment by MeetWq** [comment]
不像是频道消息造成的
这段报错后面还有吗

**Comment by WindraiteLesd** [comment]
![IMG_20230603_141218](https://github.com/noneplugin/nonebot-plugin-memes/assets/104503043/0c9eed03-2be9-489b-a804-e14d0559663c)
等了五分钟报错结束了，最后的报错是这些
频道发消息稳定触发

**Comment by jcjrobert** [comment]
请安装频道补丁插件 https://github.com/mnixry/nonebot-plugin-guild-patch
与本插件无关

**Comment by WindraiteLesd** [comment]
> 请安装频道补丁插件 https://github.com/mnixry/nonebot-plugin-guild-patch 与本插件无关

装了的

**Comment by WindraiteLesd** [comment]
> 请安装频道补丁插件 https://github.com/mnixry/nonebot-plugin-guild-patch 与本插件无关

装了的

**Comment by jcjrobert** [comment]
> > 请安装频道补丁插件 https://github.com/mnixry/nonebot-plugin-guild-patch 与本插件无关
> 
> 装了的

有成功加载吗

**Comment by WindraiteLesd** [comment]
> > > 请安装频道补丁插件 https://github.com/mnixry/nonebot-plugin-guild-patch 与本插件无关
> > 
> > 
> > 装了的
> 
> 有成功加载吗

![IMG_20230604_125335](https://github.com/noneplugin/nonebot-plugin-memes/assets/104503043/4c7586dd-e019-4635-ad5b-3b957a0e747c)
![IMG_20230604_130558](https://github.com/noneplugin/nonebot-plugin-memes/assets/104503043/4895b37b-b3b0-462e-b2af-a2cd880fbbbc)

如图，在正常加载情况下，接收到频道消息复现报错然后循环
这个问题重点其实是收到消息就刷屏报错，一秒几百条那种，后台直接卡的没法响应其它任何事件，过很久才停止报错

**Comment by MeetWq** [comment]
看上去 icqq 的频道消息格式和 gocq 有区别，[nonebot-plugin-guild-patch](https://github.com/mnixry/nonebot-plugin-guild-patch) 是适用于 gocq 的
你应该去找 icqq 有没有频道补丁或者屏蔽频道消息的方法，这和本插件无关
