### ISSUE TITLE
无法正确显示帮助

### ISSUE THREAD

**Issue by MIt-gancm** [noneplugin/nonebot-plugin-memes#55]
神奇字体都装了 其他表情能正常使用字体 终端也没有报错
![Screenshot_20230605_215149](https://github.com/noneplugin/nonebot-plugin-memes/assets/72749591/5a4d2e6d-4fdd-4779-9f4f-957999e50f17)

![Screenshot_20230605_215159](https://github.com/noneplugin/nonebot-plugin-memes/assets/72749591/0678ac3c-7c0b-4575-9d6e-222cb1f3637e)

![Screenshot_20230605_215402](https://github.com/noneplugin/nonebot-plugin-memes/assets/72749591/e3c4b215-0966-4474-9ade-2a6974543c86)

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/blob/5358f453b9b6cb1041237253eff6581149733cc4/README.md?plain=1#L106-L119
