### ISSUE TITLE
跟头像表情包一起用的时候，会发送两次图片

### ISSUE THREAD

**Issue by NAOLIU** [noneplugin/nonebot-plugin-memes#59]
我同时安装了https://github.com/noneplugin/nonebot-plugin-petpet
并且感觉有部分冲突
在使用指令的时候会同时触发两个，请问这个 表情包制作 是不包含 头像表情包 的内容，但可以扫描出对应的内容
还是说头像表情包和这个插件是两个独立的插件，只不过大部分表情和指令是重复的，只保留其中一个就行？
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/55797625/d782ea50-0337-4671-985f-a4dd88542946)

**Comment by Plasma4004** [comment]
memes v0.4是petpet和memes v0.3的整合，所以确实重复了

**Comment by Plasma4004** [comment]
可以把petpet丢进垃圾桶里（

**Comment by NAOLIU** [comment]
> 可以把petpet丢进垃圾桶里（

OK，没问题

**Comment by NAOLIU** [comment]
> memes v0.4是petpet和memes v0.3的整合，所以确实重复了

我想问一下，之前我做了一个入群欢迎，然后调用了petpet的表情包中的“摸@XXX”的表情包，我传入了图片就能返回gif，并把这个GIF发送出去用作新人欢迎
memes v0.4跟以前的结构区别有点大，能否讲一下其他插件如何调用memes v0.4实时生成表情包呢？

**Comment by MeetWq** [comment]
https://github.com/MeetWq/meme-generator/blob/main/docs/examples/test_meme.py

**Comment by NAOLIU** [comment]
> https://github.com/MeetWq/meme-generator/blob/main/docs/examples/test_meme.py

好的好的！
