### ISSUE TITLE
使用@+qq号导致的额外异常

### ISSUE THREAD

**Issue by blyc** [noneplugin/nonebot-plugin-memes#61]
![图片](https://github.com/noneplugin/nonebot-plugin-memes/assets/34291620/e3e980b4-6fa9-44c6-8ccf-af6ef0d778a5)

如图，虽然提供了@+QQ号来获取头像的功能，但似乎由于@不存在的群友导致一次异常提示？

虽然没有影响功能使用，且最终图片正确生成了，但可否对该异常进行处理 或是使用 @ 之外的符号来作为qq号输入前缀

**Comment by MeetWq** [comment]
新版本使用 `nonebot-plugin-userinfo` 插件获取头像，目前不会出现这种问题了
