### ISSUE TITLE
如何更新表情列表

### ISSUE THREAD

**Issue by YingLing3** [noneplugin/nonebot-plugin-memes#62]
根据meme-generator的文档，使用meme download下载最新表情后，也删除了/root/.cache/nonebot2/nonebot_plugin_memes下生成的列表图片，重新生成还是只有180个
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/44056856/49ec12d5-8ad4-446a-811f-80c74e6a8c57)
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/44056856/5ba91e14-bfc4-4c1e-94b2-4c749c51df56)
![1a1a376c308ce969d60810fc82898d56](https://github.com/noneplugin/nonebot-plugin-memes/assets/44056856/d0820032-c0ac-45ab-b28b-28ff619fe9bc)

**Comment by MeetWq** [comment]
meme-generator 更新了吗

**Comment by YingLing3** [comment]
已解决 还需要删除/root/.config/nonebot2/nonebot_plugin_memes内的配置文件
