### ISSUE TITLE
在服务器上使用表情包帮助直接中文乱码

### ISSUE THREAD

**Issue by ability66** [noneplugin/nonebot-plugin-memes#64]
![$R@J7_JJ4GFVMNZAJ37DNGG_tmb](https://github.com/noneplugin/nonebot-plugin-memes/assets/106503132/d3012472-a203-4fe6-a673-7ac879aa9f9c)
求助，不知道怎么解决

**Comment by ability66** [comment]
发现忘记安装字体了，但是安装之后还是显示不出来中文
![63}SF$PK KFV ~N X5@ NP2](https://github.com/noneplugin/nonebot-plugin-memes/assets/106503132/385c5c4b-9861-44bc-80e0-a61ec518e764)

**Comment by zombie110year** [comment]
你这个问题，文档里提到过。😡

[meme-generator 文档](https://github.com/MeetWq/meme-generator/blob/main/docs/install.md#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85)

首先，运行 `fc-cache -fv` 重建字体缓存。
然后删除 `~/.cache/matplotlib/fontlist-xxx.json` 文件，让其重新生成。

上面是我摘抄过来的 Linux 解决方法，如果你用的 Windows 或 MacOS，自行进入上面的链接阅读文档。

**Comment by ability66** [comment]
解决了，先没有看到😫



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月25日(周一) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [noneplugin/nonebot-plugin-memes] 在服务器上使用表情包帮助直接中文乱码 (Issue #64)




 
你这个问题，文档里提到过。😡
 
meme-generator 文档
 
首先，运行 fc-cache -fv 重建字体缓存。
 然后删除 ~/.cache/matplotlib/fontlist-xxx.json 文件，让其重新生成。
 
上面是我摘抄过来的 Linux 解决方法，如果你用的 Windows 或 MacOS，自行进入上面的链接阅读文档。

**Comment by zombie110year** [comment]
这 issue 还没 close?
