### ISSUE TITLE
[建议]会考虑添加satori或是red适配器的支持吗

### ISSUE THREAD

**Issue by Mechorca** [noneplugin/nonebot-plugin-memes#65]

**Comment by MeetWq** [comment]
新版本已添加多适配器支持，具体看 saa、alconna、session、userinfo 插件的适配情况

**Comment by MeetWq** [comment]
red适配器目前无法获取被@的人的信息

**Comment by Mechorca** [comment]
> red适配器目前无法获取被@的人的信息

可以获取到QQ号。请问有考虑用QQ自带的接口来实现这一功能吗。

**Comment by MeetWq** [comment]
考虑到通用性，这个插件不会用这种平台相关的接口，可以去 [nonebot-plugin-userinfo](https://github.com/noneplugin/nonebot-plugin-userinfo) 讨论

在 `nonebot-plugin-userinfo` 目前的接口中，`user_name` 是必须获得的，单独有qq号能获取头像，但没法获取用户名

你可以试一下这个pr中的版本，这里尝试拉取群成员的信息：https://github.com/noneplugin/nonebot-plugin-userinfo/pull/17
（但是我用 0.0.54 版本的 Chronocat 试了不行）
