### ISSUE TITLE
新表情问题

### ISSUE THREAD

**Issue by yoiyami96** [noneplugin/nonebot-plugin-memes#7]
大佬辛苦了
1.指令高情商和低情商的顺序反了
2.吴京表情字数限制太大了，我觉得可以在吴京头上加一处文本
<img src = 'https://s3.bmp.ovh/imgs/2022/06/12/eebeb2363b0c769e.png' />
<img src = 'https://s3.bmp.ovh/imgs/2022/06/12/f84f152c6ea80913.png' />

**Comment by MeetWq** [comment]
吴京表情现在其实是可以有四段文字的
比如 `吴京 测试测试测试 测试中国测试 测试测试测试`
![XXOTQMM2H4QYPSW`0)SMGYT](https://user-images.githubusercontent.com/33149974/173230102-063667ab-182e-458b-a0de-b160159e94c2.PNG)

**Comment by MeetWq** [comment]
`吴京 周日还没打剿灭的人 滚出中国`
![P79B7}~KK_E42 PSQA(R RX](https://user-images.githubusercontent.com/33149974/173230190-0fbffaff-8667-446a-a889-10167ede4876.PNG)

**Comment by yoiyami96** [comment]
> 吴京表情现在其实是可以有四段文字的 比如 `吴京 测试测试测试 测试中国测试 测试测试测试` ![XXOTQMM2H4QYPSW`0)SMGYT](https://user-images.githubusercontent.com/33149974/173230102-063667ab-182e-458b-a0de-b160159e94c2.PNG)

是我铸币了，看不懂代码，谢谢大佬，大佬牛逼！
