### ISSUE TITLE
在飞书平台未能匹配到命令

### ISSUE THREAD

**Issue by blyc** [noneplugin/nonebot-plugin-memes#72]
~~~
nonebot2                                     2.1.3
nonebot-adapter-feishu                       2.3.1
nonebot-plugin-alconna                       0.35.1
nonebot_plugin_memes                         0.5.1
nonebot-plugin-send-anything-anywhere        0.4.0
~~~
在飞书平台纯文本指令可以正常匹配，但同时带图就匹配不到了
![图片](https://github.com/noneplugin/nonebot-plugin-memes/assets/34291620/aa7a6a0b-2ac1-4290-b0a1-d0689bb4b960)
看起来似乎是因为包了一层，所以想请教下插件是否能处理或者要咨询哪个前置依赖
![图片](https://github.com/noneplugin/nonebot-plugin-memes/assets/34291620/2a3995fb-f9ec-4327-abcf-ee257d7795e8)

**Comment by MeetWq** [comment]
开 DEBUG 看一下日志？

**Comment by blyc** [comment]
感谢，更新了`adapter-feishu`到2.3.2后指令可以匹配到了

但现在发送图文消息对图片似乎没有解析，这个是我打印了一下state的值
这个问题我是该同样到adapter提issues吗？
![图片](https://github.com/noneplugin/nonebot-plugin-memes/assets/34291620/0ba0395e-89d4-4316-9a7c-7f0fb23932f9)

**Comment by MeetWq** [comment]
飞书适配器目前并没有解析富文本消息，@ 同样也没没有解析。这个要处理的话有点麻烦，但你可以先去提个 issue，看作者打算怎么解决

**Comment by blyc** [comment]
好的，万分感谢
