### ISSUE TITLE
云崽机器人报错

### ISSUE THREAD

**Issue by admimare** [noneplugin/nonebot-plugin-memes#73]
嗨~
如题 报错信息如下 请问该怎么解决
![WY6 OXLU{{ }06 MT)067}3_tmb](https://github.com/noneplugin/nonebot-plugin-memes/assets/74863664/7cbef58a-9d12-4652-b861-95fdb46f0ac0)
运行平台
小米6 安卓9
使用trss.me脚本安装
python版本3.10.10
poetry 版本1.7.1

**Comment by MeetWq** [comment]
看上去是云崽的问题，我不清楚云崽是怎么魔改的，这边不负责解决

**Comment by admimare** [comment]
> 看上去是云崽的问题，我不清楚云崽是怎么魔改的，这边不负责解决

好的  感谢解答
