### ISSUE TITLE
在加载插件时发生错误

### ISSUE THREAD

**Issue by yhzcake** [noneplugin/nonebot-plugin-memes#74]
![aa1e5bc78f239749bd63987953098475](https://github.com/noneplugin/nonebot-plugin-memes/assets/80627671/489f8fac-e869-449d-8913-153aaa89c057)
看起来是因为get请求得到的为none导致的
可能是表情包图包?我第一次初始化可能强行停止导致的吧
图包应该保存在哪里

**Comment by MeetWq** [comment]
你是用的 meme-generator + memes-api 吗？先看看 meme-generator 能不能正常使用

**Comment by yhzcake** [comment]
我是直接nb install 的

**Comment by MeetWq** [comment]
你要是用 memes-api 的话，需要另外部署 meme-generator

**Comment by yhzcake** [comment]
谢谢,我试试
