### ISSUE TITLE
制作图片表情包时出现错误

### ISSUE THREAD

**Issue by exusiai07** [noneplugin/nonebot-plugin-memes#76]
<img width="727" alt="image" src="https://github.com/noneplugin/nonebot-plugin-memes/assets/112692808/127a6d00-7f9c-4e7e-a826-12c02fa3c3d8">
文字表情包没有这个问题，所有需要用户提供图片的表情包都有这个问题

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/issues/69

**Comment by exusiai07** [comment]
> #69

感谢大佬，解决了
