### ISSUE TITLE
发送图片制作时报错

### ISSUE THREAD

**Issue by XibieTime** [noneplugin/nonebot-plugin-memes#77]
指令消息包含图片或者回复某张图片制作表情包时报错：TypeError: Current driver does not support http client
直接at用户+指令制作时不会报错

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/issues/69

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/issues/69

**Comment by XibieTime** [comment]
> #69

感谢，已正常工作
