### ISSUE TITLE
低情商高情商高情商低情商

### ISSUE THREAD

**Issue by jcjrobert** [noneplugin/nonebot-plugin-memes#8]
![99LI20)~6%9N26T~$H})K 5](https://user-images.githubusercontent.com/52129454/173475033-cda8ff3e-bccf-49dd-9065-5cc838819ffe.PNG)

**Comment by jcjrobert** [comment]
改成截取最后一个吧（

**Comment by jcjrobert** [comment]
改成截取最后一个吧（

**Comment by jcjrobert** [comment]
然后低语叫murmur更好吧我觉得

**Comment by jcjrobert** [comment]
> 改成截取最后一个吧（

好像也不太行 空格分开吧

**Comment by MeetWq** [comment]
> 然后低语叫murmur更好吧我觉得

是说改函数名吗？
这个表情不是你pr的吗（恼

**Comment by jcjrobert** [comment]
> > 然后低语叫murmur更好吧我觉得
> 
> 是说改函数名吗？ 这个表情不是你pr的吗（恼

确实，只是偶然背单词时找到了更好的，之前也不知道qwq

**Comment by jcjrobert** [comment]
> > 改成截取最后一个吧（
> 
> 现在是正则匹配的，感觉怎么改都不合适，不这样用就行了（

低情商 XX 高情商 XX 这样
