### ISSUE TITLE
更新0.6.2版本后无法正常显示中文字体

### ISSUE THREAD

**Issue by Q1351998764** [noneplugin/nonebot-plugin-memes#86]
之前的版本中文字体可以正常显示，换拉格朗日后，由于无法获取用户头像，更新至0.6.2版本，之后中文字体就会显示为方块。字体已经重新安装过，缓存也删除了，但仍然显示方块。
![9395a2ccbf7ae236234963f7834cf3b5](https://github.com/noneplugin/nonebot-plugin-memes/assets/57926506/50bc5b20-4ae4-43f5-a967-1f35b3564478)

**Comment by Q1351998764** [comment]
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/57926506/8116d365-c9d4-40a7-820a-df5168af8d3b)
高亮一下。

**Comment by MeetWq** [comment]
https://github.com/MeetWq/meme-generator/tree/main/resources/fonts

把这里面的字体都装一下再试试，
装完记得删除缓存

**Comment by Q1351998764** [comment]
字体都装上就好了，谢谢大佬。
