### ISSUE TITLE
Ubuntu22 按照文档装了字体任然乱码

### ISSUE THREAD

**Issue by HL-Light** [noneplugin/nonebot-plugin-memes#92]
![c7bcdf27da32b64dc96c75222cb73e69](https://github.com/noneplugin/nonebot-plugin-memes/assets/116658416/7cb334dc-c179-4951-ab83-50f8ce659c30)
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/116658416/566fd86b-28f1-4295-9ef3-4807c52fbf14)

**Comment by HL-Light** [comment]
我把缓存删了一遍还是没解决

**Comment by woxihuangxiaoyang** [comment]
![0b0aca37719dd8f484fef4ceae64bbb5](https://github.com/noneplugin/nonebot-plugin-memes/assets/88092738/da59306e-99d5-4272-b0ea-4ccfa1fc1d6b)
拿这张图替换就行

**Comment by MeetWq** [comment]
装一下这里的字体 https://github.com/MeetWq/meme-generator/tree/main/resources/fonts

**Comment by HL-Light** [comment]
感谢，解决了，
