### ISSUE TITLE
图片表情制作上传图片报错

### ISSUE THREAD

**Issue by HL-Light** [noneplugin/nonebot-plugin-memes#93]
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/116658416/058c1fcd-eaf0-4d43-bd29-c0f388a323c1)

![image](https://github.com/MeetWq/meme-generator/assets/116658416/d3f0adec-d379-4fb0-99d2-0fc90ff76aa1)

**Comment by HL-Light** [comment]
无头客户端是[Lagrange.Core](https://github.com/KonataDev/Lagrange.Core)，以下是我的配置信息

```
{
    "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "SignServerUrl": "https://sign.libfekit.so/api/sign",
    "Account": {
        "Uin": 0,
        "Password": "",
        "Protocol": "Linux",
        "AutoReconnect": true,
        "GetOptimumServer": true
    },
    "Message": {
      "IgnoreSelf": true, 
      "StringPost": true
    },
    "QrCode": {
        "ConsoleCompatibilityMode": false
    },
    "Implementations": [
        {
            "Type": "ReverseWebSocket",
            "Host": "127.0.0.1",
            "Port": 43992,
            "Suffix": "/onebot/v11/ws",
            "ReconnectInterval": 5000,
            "HeartBeatInterval": 5000,
            "AccessToken": ""
        }
    ]
}
```

**Comment by MeetWq** [comment]
我用你这个版本的 lagrange 试了没问题，你检查一下 `nonebot-plugin-memes` 的版本；
可以换个图片试试，有可能是图片的问题

**Comment by HL-Light** [comment]
nonebot-plugin-memes版本是0.6.2，我尝试了如下图片都返回了同样的报错信息

![D41EAE56CF903495F1BA99F86F8941EE](https://github.com/noneplugin/nonebot-plugin-memes/assets/116658416/a222df65-8a57-472a-89e6-dcaea3dace12)

**Comment by MeetWq** [comment]
你再确认一下收到的图片中有没有`url`

**Comment by HL-Light** [comment]
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/116658416/becaf7a2-36bf-45fa-a3ce-764171a49099)
这应该有收到url吧

**Comment by MeetWq** [comment]
> ![image](https://private-user-images.githubusercontent.com/116658416/320264161-becaf7a2-36bf-45fa-a3ce-764171a49099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkwMzcsIm5iZiI6MTcxMjQ3ODczNywicGF0aCI6Ii8xMTY2NTg0MTYvMzIwMjY0MTYxLWJlY2FmN2EyLTM2YmYtNDVmYS1hM2NlLTc2NDE3MWE0OTA5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODMyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0MGNlZGRkMmU1NTVkMmQxZTM2MTFhY2Q0OGIzZWFiYWE1OTU4ODBkMGM1NDk2NTJiMTE1YzMxMjNhYjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uXZrriITYaB6aUuxNJD0IOkGaU2hKBWpKkmEphKGok0) 这应该有收到url吧

你这个只有 file=xxx，没有 url=xxx

我不知道为什么会缺，我用你发的 lagrange 试了是没问题的

**Comment by MeetWq** [comment]
你把 lagrange 配置中 `StringPost` 改成 `false` 试试

**Comment by HL-Light** [comment]
感谢，成功解决了
