### ISSUE TITLE
艾特机器人要用艾特两次才能生效

### ISSUE THREAD

**Issue by BraveCowardp** [noneplugin/nonebot-plugin-memes#94]
使用的qq客户端是docker部署的[LLOneBot](https://github.com/LLOneBot/LLOneBot)
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/61410850/27d2397b-fcc7-4daf-926e-3fc414b0315b)
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/61410850/eef70065-1371-4ace-9f9d-cde220aea09e)

**Comment by MeetWq** [comment]
这是因为 onebot 适配器会删掉末尾的@机器人，属于预期行为

**Comment by BraveCowardp** [comment]
> 这是因为 onebot 适配器会删掉末尾的@机器人，属于预期行为

好的，感谢
