### ISSUE TITLE
回复图片制作表情包时报错

### ISSUE THREAD

**Issue by hiroshihuang** [noneplugin/nonebot-plugin-memes#96]
![Screenshot_2024-04-29-01-04-10-456_com tencent mobileqq](https://github.com/noneplugin/nonebot-plugin-memes/assets/164932517/0068eff2-6ded-4e44-8cf2-e62613975973)
![Screenshot_2024-04-29-01-04-47-024_com server auditor ssh client](https://github.com/noneplugin/nonebot-plugin-memes/assets/164932517/165c7f6d-927e-4130-8551-408177452110)
![Screenshot_2024-04-29-01-04-43-391_com server auditor ssh client](https://github.com/noneplugin/nonebot-plugin-memes/assets/164932517/263c1f21-39cd-4f67-b6eb-99e59129f17c)

**Comment by hiroshihuang** [comment]
使用的是无头napcat和onebotV11

**Comment by MeetWq** [comment]
qq 用了新的图床，加了 rkey 参数，导致图片无法直接下载；
因此不止是回复图片，直接发图片也会报错；
目前用 pc 端 qq 发出来的图片还是旧图床，是没问题的。
这不是插件的锅，目前得等等看协议端怎么解决，napcat 下个版本估计会解决。
