### ISSUE TITLE
[不确定是不是bug]安装新字体后清理缓存后还是不行

### ISSUE THREAD

**Issue by yhzcake** [noneplugin/nonebot-plugin-memes#97]
![image](https://github.com/noneplugin/nonebot-plugin-memes/assets/80627671/cce21db1-56bf-4afa-927e-030649f4c389)
https://github.com/MeetWq/meme-generator/issues/100
matplotlib和插件这边的缓存都有清理过,但是还是不行

**Comment by MeetWq** [comment]
nonebot 重启过了没？如果还是不行可以主页的QQ群

**Comment by yhzcake** [comment]
> nonebot 重启过了没？如果还是不行可以主页的QQ群

额,没找到qq群
